name: Build backend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/narah111/ocp-guestbook/

jobs:

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set platform based on branch
        id: platform
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.base_ref }}" == "main" ]; then
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
            echo "Building for amd64 (PR to main)"
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "platforms=linux/arm64" >> $GITHUB_OUTPUT
            echo "Building for arm64 (develop branch)"
          else
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
            echo "Building for amd64 (default)"
          fi

      - name: QEMU Setup
        uses: docker/setup-qemu-action@v3
        with:
            platforms: ${{ steps.platform.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
            context: ./backend
            file: ./backend/Containerfile
            platforms: ${{ steps.platform.outputs.platforms }}
            push: ${{ github.event_name != 'pull_request' }}
            
            tags: |
                ghcr.io/narah111/ocp-guestbook/backend:latest
                ghcr.io/narah111/ocp-guestbook/backend:${{ github.sha }}